# Minimal config (edit per your environment)
seed: 42
retrieval:
  top_k: 10
  hybrid_weights: [0.5, 0.5]   # [BM25, Dense]
  chunk:
    size: 300
    overlap: 60
models:
  dense: "sentence-transformers/all-MiniLM-L6-v2"   # placeholder
  reranker: "cross-encoder/ms-marco-MiniLM-L-6-v2"  # placeholder
data:
  corpus_path: "./data/corpus.jsonl"  # one JSON per line: {"id": "...","text": "..."} 
  qrels_path: "./data/qrels.jsonl"    # {"qid":"...","doc_id":"...","rel":1}
  queries_path: "./data/queries.jsonl"# {"id":"...","question":"..."}
